
library(tidyverse)
library(lubridate)

# Directory to contain all target metadata files
directory <- "D:/SERDP/Huachuca/Planet/output_imagery"

# Read in all files in target directory
filenames <- list.files(path=directory, pattern="*.xml")
# Drop any .xml files which are autogenerated by QGIS and don't actually contain metadata:
filenames <- filenames[-grep("*aux*", filenames)]

dates <- integer()
class(dates) <- "Date"

metadata <- data.frame(
  file = character(),
  sensor_angle = numeric(),
  sun_azimuth = numeric(),
  sun_elevation = numeric(),
  date = dates,
  year = integer(),
  month = integer(),
  day = integer())
for(filename in filenames)
{
  file_text <- readLines(paste(directory, filename, sep="/"))

  new_observation <- data.frame(
    file = filename,
    sensor_angle = NA,
    sun_azimuth = NA,
    sun_elevation = NA,
    date = NA,
    year = NA,
    month = NA,
    day = NA,
    hour = NA,
    minute = NA)
  
  # Get Sun Angle
  line_num <- grep("<eop:incidenceAngle uom=\"deg\">.*</eop:incidenceAngle>", file_text)
  if(length(line_num) > 0)
  {
    new_observation$sensor_angle <- as.numeric(str_extract(file_text[[line_num]], "[\\d]+.[\\d]+.{2}[\\d]+"))
  }
  
  # Get Solar Azimuth
  line_num <- grep("<opt:illuminationAzimuthAngle uom=\"deg\">.*</opt:illuminationAzimuthAngle>", file_text)
  if(length(line_num) > 0)
  {
    new_observation$sun_azimuth <- as.numeric(str_extract(file_text[[line_num]], "[\\d]+.[\\d]+.{2}[\\d]+"))
  }
  
  # Get Solar Elevation 
  line_num <- grep("<opt:illuminationElevationAngle uom=\"deg\">.*</opt:illuminationElevationAngle>", file_text)
  if(length(line_num) > 0)
  {
    new_observation$sun_elevation <- as.numeric(str_extract(file_text[[line_num]], "[\\d]+.[\\d]+.{2}[\\d]+"))
  }
  
  # Get Date
  line_num <- grep("<ps:acquisitionDateTime>.*</ps:acquisitionDateTime>", file_text)
  if(length(line_num) > 0)
  {
    new_observation$date <- as.Date(str_extract(file_text[[line_num]], "[\\d]{4}-[\\d]{2}-[\\d]{2}"))
  }
  # Get Time
  if(length(line_num) > 0)
  {
    time <- str_extract(file_text[[line_num]], "T[\\d]{2}:[\\d]{2}")
    new_observation$hour <- as.numeric(substr(time, 2, 3))
    new_observation$minute <- as.numeric(substr(time, 5, 6))
  }
  
  metadata <- rbind(metadata, new_observation)
}

metadata$year <- as.numeric(substr(as.character(metadata$date),1,4))
metadata$month <- as.numeric(substr(as.character(metadata$date),6,7))
metadata$day <- as.numeric(substr(as.character(metadata$date),9,10))
metadata$doy <- lubridate::yday(metadata$date)

metadata <- metadata %>% drop_na()